# Generated by Django 4.0.1 on 2022-01-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planningApp', '0002_remove_dailyplan_agronomist_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='annotation',
        ),
    ]
