# Generated by Django 4.0.1 on 2022-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Adilabad', 'Adilabad'), ('Bhadradri Kothagudem', 'Bhadradri Kothagudem'), ('Hanumakonda', 'Hanumakonda'), ('Hyderabad', 'Hyderabad'), ('Jagtial', 'Jagtial'), ('Jangaon', 'Jangaon'), ('Jayashankar Bhupalpally', 'Jayashankar Bhupalpally'), ('Jogulamba Gadwal', 'Jogulamba Gadwal'), ('Kamareddy', 'Kamareddy'), ('Karimnagar', 'Karimnagar'), ('Khammam', 'Khammam'), ('Kumuram Bheem', 'Kumuram Bheem'), ('Mahabubabad', 'Mahabubabad'), ('Mahabubnagar', 'Mahabubnagar'), ('Mancherial', 'Mancherial'), ('Medak', 'Medak'), ('Medchal-Malkajgiri', 'Medchal-Malkajgiri'), ('Mulugu', 'Mulugu'), ('Nagarkurnool', 'Nagarkurnool'), ('Nalgonda', 'Nalgonda'), ('Narayanpet', 'Narayanpet'), ('Nirmal', 'Nirmal'), ('Nizamabad', 'Nizamabad'), ('Peddapalli', 'Peddapalli'), ('Rajanna Sircilla', 'Rajanna Sircilla'), ('Rangareddy', 'Rangareddy'), ('Sangareddy', 'Sangareddy'), ('Siddipet', 'Siddipet'), ('Suryapet', 'Suryapet'), ('Vikarabad', 'Vikarabad'), ('Wanaparthy', 'Wanaparthy'), ('Warangal', 'Warangal'), ('Yadadri Bhuvanagiri', 'Yadadri Bhuvanagiri')], max_length=100)),
                ('humidity', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WaterIrrigationSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Adilabad', 'Adilabad'), ('Bhadradri Kothagudem', 'Bhadradri Kothagudem'), ('Hanumakonda', 'Hanumakonda'), ('Hyderabad', 'Hyderabad'), ('Jagtial', 'Jagtial'), ('Jangaon', 'Jangaon'), ('Jayashankar Bhupalpally', 'Jayashankar Bhupalpally'), ('Jogulamba Gadwal', 'Jogulamba Gadwal'), ('Kamareddy', 'Kamareddy'), ('Karimnagar', 'Karimnagar'), ('Khammam', 'Khammam'), ('Kumuram Bheem', 'Kumuram Bheem'), ('Mahabubabad', 'Mahabubabad'), ('Mahabubnagar', 'Mahabubnagar'), ('Mancherial', 'Mancherial'), ('Medak', 'Medak'), ('Medchal-Malkajgiri', 'Medchal-Malkajgiri'), ('Mulugu', 'Mulugu'), ('Nagarkurnool', 'Nagarkurnool'), ('Nalgonda', 'Nalgonda'), ('Narayanpet', 'Narayanpet'), ('Nirmal', 'Nirmal'), ('Nizamabad', 'Nizamabad'), ('Peddapalli', 'Peddapalli'), ('Rajanna Sircilla', 'Rajanna Sircilla'), ('Rangareddy', 'Rangareddy'), ('Sangareddy', 'Sangareddy'), ('Siddipet', 'Siddipet'), ('Suryapet', 'Suryapet'), ('Vikarabad', 'Vikarabad'), ('Wanaparthy', 'Wanaparthy'), ('Warangal', 'Warangal'), ('Yadadri Bhuvanagiri', 'Yadadri Bhuvanagiri')], max_length=100)),
                ('water_qty', models.IntegerField(default=0)),
            ],
        ),
    ]
