# Generated by Django 4.0 on 2022-01-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steeringinitiative',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
