# Generated by Django 4.0 on 2022-01-21 11:12

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('reportApp', '0002_steeringinitiative_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steeringinitiative',
            name='report',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='reports/'),
        ),
    ]
