# Generated by Django 4.0 on 2021-12-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_user_district'),
        ('planningApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='agronomist_user_id',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='farmer_user_id',
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='agronomist_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agronomist_user', to='userApp.user'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='visit_farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_farmer', to='userApp.user'),
        ),
    ]
