# Generated by Django 4.0 on 2022-01-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_steeringinitiative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
