# Generated by Django 4.0 on 2021-12-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_helprequest_date_steeringinitiative_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPlan',
        ),
    ]
