# Generated by Django 4.0 on 2022-01-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_id_farm_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SteeringInitiative',
        ),
    ]
